version: 2.1

orbs:
  node: circleci/node@4

jobs:
  test_and_build:
    description: Install deps, run tests & build the React app
    executor:
      name: node/default
      tag: '18.20.8'
    steps:
      - checkout

      - node/with-cache:
          steps:
            - run:
                name: Install dependencies
                command: npm install --legacy-peer-deps

      - run:
          name: Run tests
          command: npm test -- --watchAll=false --ci

      - run:
          name: Build production bundle
          command: npm run build

      - persist_to_workspace:
          root: .
          paths:
            - build

workflows:
  version: 2
  pr-check:
    jobs:
      - test_and_build:
          filters:
            branches:
              ignore:
                - main
            tags:
              ignore:
                - /.*/
