version: 2.1

orbs:
  node: circleci/node@4

jobs:
  test_and_build:
    description: Install dependencies, run tests, then build the React app
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install dependencies
                command: |
                  if [ -f yarn.lock ]; then
                    yarn install --frozen-lockfile
                  else
                    npm ci
                  fi
      - run:
          name: Run tests
          command: |
            if [ -f yarn.lock ]; then
              yarn test -- --watchAll=false --ci
            else
              npm test -- --watchAll=false --ci
            fi
      - run:
          name: Build production bundle
          command: |
            if [ -f yarn.lock ]; then
              yarn build
            else
              npm run build
            fi
      - persist_to_workspace:
          root: .
          paths:
            - build

workflows:
  version: 2
  pr-check:
    jobs:
      - test_and_build:
          filters:
            branches:
              ignore: /.*/
            pull-requests:
              only: /.*/