version: 2.1

orbs:
  node: circleci/node@4

jobs:
  test_and_build:
    description: Install dependencies, run tests, then build the React app
    executor:
      name: node/default
    steps:
      - checkout

      - node/with-cache:
          steps:
            - run:
                name: Install dependencies
                command: yarn install --frozen-lockfile

      - run:
          name: Run tests
          command: yarn test -- --ci --watchAll=false

      - run:
          name: Build production bundle
          command: yarn build

      - persist_to_workspace:
          root: .
          paths:
            - build

workflows:
  version: 2
  pr-check:
    jobs:
      - test_and_build:
          filters:
            branches:
              ignore:
                - main
            tags:
              ignore:
                - /.*/
